// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABDG4LszorQ1vhnP5FFbyTzPJjND7kjkI',
    appId: '1:207376636349:web:f87baa83b8ce58e1171ad4',
    messagingSenderId: '207376636349',
    projectId: 'pizza-ffc84',
    authDomain: 'pizza-ffc84.firebaseapp.com',
    databaseURL: 'https://pizza-ffc84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pizza-ffc84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3kNia4oUqf3XGPFHkcyDS6dfjC7hej9c',
    appId: '1:207376636349:android:bc8351974802ff8c171ad4',
    messagingSenderId: '207376636349',
    projectId: 'pizza-ffc84',
    databaseURL: 'https://pizza-ffc84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pizza-ffc84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDPYxmV44Vj2GVjlkItwk-9De9cewzHE',
    appId: '1:207376636349:ios:e8e3a45f2b6a577b171ad4',
    messagingSenderId: '207376636349',
    projectId: 'pizza-ffc84',
    databaseURL: 'https://pizza-ffc84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pizza-ffc84.appspot.com',
    iosClientId: '207376636349-pd27s9r34hgesidod5tq556fs4u57beq.apps.googleusercontent.com',
    iosBundleId: 'com.wanjawischmeier.pizzaFlizza',
  );
}
